// pages/index.js
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/index.module.css'

export default function Home(props) {

  return (
    <div className="container">
      
      <Head>

        <title>ESI</title>
        <link rel="" href=""/>

      </Head>

      <div className={styles.home}>
        <h2>
          Welcome to Gardner’s Effect Size Illustrator (version 1.2).
        </h2>
        <p>
          In the fields of health, psychology, and education, many important outcomes are expressed in shades of gray as opposed to black and white. These shades of gray (e.g., mental and physical suffering and disability) are frequently reported in terms of “effect size”, which, despite its growing use, is not a particularly intuitive expression.
          The Effect Size Illustrator (ESI) is an interactive tool that helps with the practical interpretation of effect sizes. It can be used when two or more groups are being compared using continuous measures (e.g., weight, exercise duration, pain).
          You can get started right away by clicking “Effect Size Illustrator”. You’ll quickly realize that customizing your calculations and illustrations is straightforward.
          Refer to the menu to read more about the ESI and about effect size.
        </p>
        <Link href="/illustrator">
            <button className={styles.button} href="/illustrator">Go to Effect Size Illustrator 👉</button>
        </Link>
      </div>
    </div>
  )
}//Combine Home and what's ESI together




































/*import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}*/
